Version: "2"
services:
  guacamole:
    image: guacamole
    container_name: guacamole
    environment:
      - EXTENSIONS=auth-ldap,auth-totp
    volumes:
      - /conf:/config
    ports:
      - 8080:8080
    networks:
      - guacamole-letsencrypt
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VALIDATION=http
      - DHLEVEL=4096
    volumes:
      - /config:/config
    ports:
      - 1443:443  # Use a different host port (e.g., 1443) for HTTPS
    networks:
      - guacamole-letsencrypt

networks:
  guacamole-letsencrypt:
    driver: bridge
